import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Render the application's root HTML layout and provider wrappers.
 *
 * @param children - Page content to be rendered inside the root `<body>` element
 * @returns The top-level JSX element that wraps `children` with `NuqsAdapter` and `TRPCReactProvider`, provides an `<html lang="en" suppressHydrationWarning">` / `<body>` structure using the Inter font, and mounts a `Toaster` component
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
    <TRPCReactProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
    <Toaster />
    </TRPCReactProvider>
    </NuqsAdapter>
  );
}